### ISSUE TITLE
Build error missing meta-imx8mp-isp

### ISSUE THREAD

**Issue by pbilstein** [compulab-yokneam/meta-bsp-imx8mp#27]
Hello,

we are currently evaluating the Yocto support of our IOT-GATE-IMX8PLUS devices.

I have followed the official READMEs from [here](https://github.com/compulab-yokneam/yocker) and [here](https://github.com/compulab-yokneam/meta-bsp-imx8mp/blob/iot-gate-imx8plus_r3.0/README.md), but always get an error when I try to build an image with bitbake:

```
compulab@739abf8c82da:/work/in-work/build-iot-gate-imx8plus$ bitbake -k imx-image-full
ERROR: The following layer directories do not exist:
ERROR:    /work/in-work/sources/meta-imx8mp-isp
ERROR: Please check BBLAYERS in /work/in-work/build-iot-gate-imx8plus/conf/bblayers.conf
```

I tried two docker containers, ubuntu 20.04 and 22.04. Am I missing any configuration or steps?

**Comment by vraevsky** [comment]
Thank for reporting on the issue.

Fixed by:
https://github.com/compulab-yokneam/meta-bsp-imx8mp/commit/b7d7b485189270482e98a906f4d5f867c8fcbec7
https://github.com/compulab-yokneam/meta-bsp-imx8mp/commit/5f06a84f4233be1b5e7f1cc003be5f6bef1209f6

How to proceed)
Option 1) 
Update the already created build environment by issuing this command:
**sed -i '/meta-imx8mp-isp/d'  ${BUILDDIR}/conf/bblayers.conf**
Option 2)
Recreate build environment.

Sorry for that inconvenience.
